#!/usr/bin/python3
"""
UTF-8 Validation module
"""

def validUTF8(data):
        """
            Determines if a given data set represents a valid UTF-8 encoding.
                
                    :param data: List of integers representing the data bytes
                        :return: True if data is a valid UTF-8 encoding, else False
                            """
                                n_bytes = 0
                                    mask1 = 1 << 7
                                        mask2 = 1 << 6

                                            for num in data:
                                                        byte = num & 0xFF

                                                                if n_bytes == 0:
                                                                                if (byte & mask1) == 0:
                                                                                                    continue
                                                                                                            elif (byte & mask1) and (byte & mask2) == 0:
                                                                                                                                return False
                                                                                                                                        else:
                                                                                                                                                            n_ones = 0
                                                                                                                                                                            mask = mask1
                                                                                                                                                                                            while byte & mask:
                                                                                                                                                                                                                    n_ones += 1
                                                                                                                                                                                                                                        mask >>= 1
                                                                                                                                                                                                                                                        if n_ones == 1 or n_ones > 4:
                                                                                                                                                                                                                                                                                return False
                                                                                                                                                                                                                                                                                            n_bytes = n_ones - 1
                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                    if not (byte & mask1 and not (byte & mask2)):
                                                                                                                                                                                                                                                                                                                                        return False
                                                                                                                                                                                                                                                                                                                                                n_bytes -= 1

                                                                                                                                                                                                                                                                                                                                                    return n_bytes == 0

                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                        # Test cases can be added here for testing
                                                                                                                                                                                                                                                                                                                                                            print(validUTF8([197, 130, 1]))  # Expected output: True
                                                                                                                                                                                                                                                                                                                                                                print(validUTF8([235, 140, 4]))  # Expected output: False
                                                                                                                                                                                                                                                                                                                                                                #!/usr/bin/python3
                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                UTF-8 Validation module
                                                                                                                                                                                                                                                                                                                                                                """

                                                                                                                                                                                                                                                                                                                                                                def validUTF8(data):
                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                            Determines if a given data set represents a valid UTF-8 encoding.
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                    :param data: List of integers representing the data bytes
                                                                                                                                                                                                                                                                                                                                                                                        :return: True if data is a valid UTF-8 encoding, else False
                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                n_bytes = 0
                                                                                                                                                                                                                                                                                                                                                                                                    mask1 = 1 << 7
                                                                                                                                                                                                                                                                                                                                                                                                        mask2 = 1 << 6

                                                                                                                                                                                                                                                                                                                                                                                                            for num in data:
                                                                                                                                                                                                                                                                                                                                                                                                                        byte = num & 0xFF

                                                                                                                                                                                                                                                                                                                                                                                                                                if n_bytes == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (byte & mask1) == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif (byte & mask1) and (byte & mask2) == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            n_ones = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mask = mask1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while byte & mask:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    n_ones += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mask >>= 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if n_ones == 1 or n_ones > 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            n_bytes = n_ones - 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not (byte & mask1 and not (byte & mask2)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                n_bytes -= 1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return n_bytes == 0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Test cases can be added here for testing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(validUTF8([197, 130, 1]))  # Expected output: True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(validUTF8([235, 140, 4]))  # Expected output: False

